repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: flake8
    - id: check-byte-order-marker
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
  - repo: https://github.com/grantjenks/blue.git
    rev: v0.8.0
    hooks:
    - id: blue

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: pytest
        types: [ python ]
        pass_filenames: false
        always_run: true
